<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>PluginExample</RootNamespace>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.9"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\mcadmin\API\src\McAdminPlugins.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\background.png" />
      <_ContentIncludedByDefault Remove="wwwroot\exampleJsInterop.js" />
    </ItemGroup>

</Project>
